### ISSUE TITLE
Performance issue for big lists of elements

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#430]
When I have 400 elements to match `find` method is much more slower then `getDriver().findElements`

It occurs when find is invoked multiple times on infinite list.

**Comment by filipcynarski** [comment]
I have reproduced the issue on Unit test level.

It was caused by invalid usage of `AbstractList<FluentWebElement>` where we implemented find and el's in get and size methods.

Currently FluentLenium is shipped w/ elements list objects and matchers so it should be refactored to use it in new manner.

**Comment by aquddos123** [comment]
We recently migrated from a very old version of Fluentlenium v0.10.3 to v3.4.1 along with Selenium from v2.53.1 to v3.6.0. We are still seeing huge performance issues with our regression builds after the upgrade. The builds are taking almost double time to finish now. Any idea what's going on?

We use to have findFirst() and find() which are now replaced with find() and some places we are using el() and $(). We mostly need to rely on nested searches like few given below for example.  

FluentList<FluentWebElement> elementList = find("li", withId().contains("some ID"), withText().contains("some text")).find("ol > li", withId().contains("some ID"));

find("li", withId().contains("some ID")).find("ol > li", withId().contains("some ID")).first().text()

el("li", withId().contains("some ID")).attribute("class");

el("#something").el("#something").find("li#ID").find("span", withText("some text")).click();

All of the above were much much efficient in the older version with find() and findFirst(). I know this is an older ticket but thought of asking here first before creating any new ticket. Please advise.

Thanks, AQ
